### ISSUE TITLE
C function parameter names lost in translation

### ISSUE THREAD

**Issue by cznic** [xlab/cgogen#10]
Maybe I just cannot find the knob, but all generated functions have parameters named like `argN`, where `N` is the 0-based index of the parameter. For documentation purposes it would be probably better to keep the original C parameter names. I realize there may be name clashes. [Elsewhere](https://github.com/cznic/c/blob/021422a28a00ebdd022698a98b6b393b916db259/internal/ccgo/ccgo.go#L11) I'm using a simple strategy in which all unexported names, like function parameter names, are simply prefixed by an underscore. The translated function parameter names would be kind of ugly, say 

```
func Copy(_dest, _src *Foo)
```

but it would retain the valuable hint about the meaning of the parameter.

Thoughts?

**Comment by xlab** [comment]
Hey @cznic, it seems that you have a header where functions have no parameter names, otherwise I cannot see the true reason of this behaviour.

For example, take any binding I ever made, there are parameter names, moreover, they are protected from collisions.
https://github.com/vulkan-go/vulkan/blob/master/vulkan.go

**Comment by xlab** [comment]
The problem with name mangling is that it makes the code unreadable, however the motto of cgogen is "to generate bindings as if a real person wrote them", i.e. the code must be suitable for reading, modifying and re-using by humans.

**Comment by cznic** [comment]
You're right. I completely missed that the header file declares only parameter types, but no names. Very unfortunate. FTR: It's gmp and it looks, for example, like this (`/usr/include/x86_64-linux-gnu/gmp.h:1249`):

```c
/**************** Float (i.e. F) routines.  ****************/

#define mpf_abs __gmpf_abs
__GMP_DECLSPEC void mpf_abs (mpf_ptr, mpf_srcptr);

#define mpf_add __gmpf_add
__GMP_DECLSPEC void mpf_add (mpf_ptr, mpf_srcptr, mpf_srcptr);

...
```
