### ISSUE TITLE
Issue with code to convert C char** to Go []string 

### ISSUE THREAD

**Issue by deepakjois** [xlab/cgogen#7]
declaration in C header file:
```
HB_EXTERN const char **
hb_shape_list_shapers (void);
```

generated code in Go:

```Go
// ShapeListShapers function as declared in harfbuzz/hb-shape.h:72
func ShapeListShapers() []string {
	__ret := C.hb_shape_list_shapers()
	var __v []string
	packSString(__v, __ret)
	return __v
}
```

but if you notice the `packSString` function below, it appears that the code will never go through the loop (`v` is always `nil`). Is that a correct deduction, or am I missing something? 

```Go
// packSString reads sliced Go data structure out from plain C format.
func packSString(v []string, ptr0 **C.char) {
	const m = 0x7fffffff
	for i0 := range v {
		ptr1 := (*(*[m / sizeOfPtr]*C.char)(unsafe.Pointer(ptr0)))[i0]
		v[i0] = packPCharString(ptr1)
	}
}
```

What we need is a Go equivalent of:

```C
  const char **shaper_list = hb_shape_list_shapers ();
  int i = 0;

  for (; *shaper_list; shaper_list++) {
    i++;    
    // FIXME Push onto Go slice here
  }
  return i;
}
```

Is that possible?

**Comment by deepakjois** [comment]
This seems to be occuring in other places as well. Here is another example of a nil slice being sent to the packing function (which will effectively return an empty slice as a return value):

```Go
// BufferGetGlyphInfos function as declared in harfbuzz/hb-buffer.h:372
func BufferGetGlyphInfos(buffer *Buffer, length *uint32) []GlyphInfo {
	cbuffer, _ := (*C.hb_buffer_t)(unsafe.Pointer(buffer)), cgoAllocsUnknown
	clength, _ := (*C.uint)(unsafe.Pointer(length)), cgoAllocsUnknown
	__ret := C.hb_buffer_get_glyph_infos(cbuffer, clength)
	var __v []GlyphInfo
	packSGlyphInfo(__v, __ret)
	return __v
}
```

**Comment by xlab** [comment]
Oh, there is nothing that can help with deducting the length of the returning array, as you can guess there is no Go analog for `for (; *shaper_list; shaper_list++)` and never will be. With plain types that are stored contiguously in memory like `[]float32` the pack methods just creates a slice-view with quite large cap, the length can be later set by user by slicing.

As for this case, that's an array of complex types and they need to be packed one-by-one, and only you know the limit. So, the only option here is to actually copy that snippet into a separate file and complete it, like that:

```go
// BufferGetGlyphInfos function as declared in harfbuzz/hb-buffer.h:372
func BufferGetGlyphInfos(buffer *Buffer, length *uint32) []GlyphInfo {
    cbuffer, _ := (*C.hb_buffer_t)(unsafe.Pointer(buffer)), cgoAllocsUnknown
    clength, _ := (*C.uint)(unsafe.Pointer(length)), cgoAllocsUnknown
    __ret := C.hb_buffer_get_glyph_infos(cbuffer, clength)
    var __v = make([]GlyphInfo, length)
    packSGlyphInfo(__v, __ret)
    return __v
}
```

Voilá! An exercise to the reader: make the original method private, so it won't cause a name collision whereas will trigger helper func generation (like `packSGlyphInfo`).
